[package]
name = "ply-rs"
version = "0.1.0"
authors = ["Felice Serena <felice@serena-mueller.ch>"]
build = "build.rs"

[dependencies]
linked-hash-map = "0.4.2"
byteorder = "1.0.0"

[build-dependencies]
peg = "0.5.3"

[[example]]
name = "read_ply"

[[example]]
name = "read_ply_header_only"
